// <auto-generated />
using System;
using Kollity.Services.Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kollity.Services.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240426155955_AddRoomMessageTypeColumnToRoomMessageTable")]
    partial class AddRoomMessageTypeColumnToRoomMessageTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("services")
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_date");

                    b.Property<byte>("Degree")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint")
                        .HasDefaultValue((byte)20)
                        .HasColumnName("degree");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4095)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<DateTime>("LastUpdateDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_update_date");

                    b.Property<int>("Mode")
                        .HasColumnType("int")
                        .HasColumnName("mode");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("name");

                    b.Property<DateTime>("OpenUntilDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("open_until_date");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("pk_assigment");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_assigment_doctor_id");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_assigment_room_id");

                    b.ToTable("Assigment", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("AssignmentGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_group_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_id");

                    b.Property<byte?>("Degree")
                        .HasColumnType("tinyint")
                        .HasColumnName("degree");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)")
                        .HasColumnName("file");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("upload_date");

                    b.HasKey("Id")
                        .HasName("pk_assignment_answer");

                    b.HasIndex("AssignmentGroupId")
                        .HasDatabaseName("ix_assignment_answer_assignment_group_id");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_answer_assignment_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_assignment_answer_student_id");

                    b.ToTable("AssignmentAnswer", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentAnswerDegree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AnswerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("answer_id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_id");

                    b.Property<byte>("Degree")
                        .HasColumnType("tinyint")
                        .HasColumnName("degree");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("group_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_answer_degree");

                    b.HasIndex("AnswerId")
                        .HasDatabaseName("ix_assignment_answer_degree_answer_id");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_answer_degree_assignment_id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_assignment_answer_degree_group_id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("ix_assignment_answer_degree_student_id");

                    b.ToTable("AssignmentAnswerDegree", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentFile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("upload_date");

                    b.HasKey("Id")
                        .HasName("pk_assignment_file");

                    b.HasIndex("AssignmentId")
                        .HasDatabaseName("ix_assignment_file_assignment_id");

                    b.ToTable("AssignmentFile", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentGroupModels.AssignmentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("code");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Code"));

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_group");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_group_code");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_assignment_group_room_id");

                    b.ToTable("AssignmentGroup", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentGroupModels.AssignmentGroupStudent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssignmentGroupId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assignment_group_id");

                    b.Property<bool>("JoinRequestAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("join_request_accepted");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_assignment_group_student");

                    b.HasIndex("AssignmentGroupId")
                        .HasDatabaseName("ix_assignment_group_student_assignment_group_id");

                    b.HasIndex("StudentId", "AssignmentGroupId")
                        .IsUnique()
                        .HasDatabaseName("ix_assignment_group_student_student_id_assignment_group_id");

                    b.ToTable("AssignmentGroupStudent", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.CourseModels.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<int>("Code")
                        .HasColumnType("int")
                        .HasColumnName("code");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("department");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<int>("Hours")
                        .HasColumnType("int")
                        .HasColumnName("hours");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_course");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_course_code");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_course_doctor_id");

                    b.ToTable("Course", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.CourseModels.CourseAssistant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AssistantId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assistant_id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.HasKey("Id")
                        .HasName("pk_course_assistant");

                    b.HasIndex("AssistantId")
                        .HasDatabaseName("ix_course_assistant_assistant_id");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_course_assistant_course_id");

                    b.HasIndex("CourseId", "AssistantId")
                        .IsUnique()
                        .HasDatabaseName("ix_course_assistant_course_id_assistant_id");

                    b.ToTable("CourseAssistant", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.Exam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("creation_date");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("end_date");

                    b.Property<DateTime>("LastUpdatedDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_updated_date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_exam");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_exam_room_id");

                    b.ToTable("Exam", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.ExamAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exam_id");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exam_question_id");

                    b.Property<Guid?>("ExamQuestionOptionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exam_question_option_id");

                    b.Property<DateTime>("RequestTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("request_time");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.Property<DateTime?>("SubmitTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("submit_time");

                    b.HasKey("Id")
                        .HasName("pk_exam_answer");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_answer_exam_id");

                    b.HasIndex("ExamQuestionId")
                        .HasDatabaseName("ix_exam_answer_exam_question_id");

                    b.HasIndex("ExamQuestionOptionId")
                        .HasDatabaseName("ix_exam_answer_exam_question_option_id");

                    b.HasIndex("StudentId", "ExamQuestionId")
                        .IsUnique()
                        .HasDatabaseName("ix_exam_answer_student_id_exam_question_id")
                        .HasFilter("[student_id] IS NOT NULL");

                    b.ToTable("ExamAnswer", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.ExamQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<byte>("Degree")
                        .HasColumnType("tinyint")
                        .HasColumnName("degree");

                    b.Property<Guid>("ExamId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exam_id");

                    b.Property<int>("OpenForSeconds")
                        .HasColumnType("int")
                        .HasColumnName("open_for_seconds");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)")
                        .HasColumnName("question");

                    b.HasKey("Id")
                        .HasName("pk_exam_question");

                    b.HasIndex("ExamId")
                        .HasDatabaseName("ix_exam_question_exam_id");

                    b.ToTable("ExamQuestion", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.ExamQuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("ExamQuestionId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("exam_question_id");

                    b.Property<bool>("IsRightOption")
                        .HasColumnType("bit")
                        .HasColumnName("is_right_option");

                    b.Property<string>("Option")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)")
                        .HasColumnName("option");

                    b.HasKey("Id")
                        .HasName("pk_exam_question_option");

                    b.HasIndex("ExamQuestionId")
                        .HasDatabaseName("ix_exam_question_option_exam_question_id");

                    b.ToTable("ExamQuestionOption", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.Identity.BaseUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<bool>("EnabledEmailNotifications")
                        .HasColumnType("bit")
                        .HasColumnName("enabled_email_notifications");

                    b.Property<string>("FullNameInArabic")
                        .HasMaxLength(127)
                        .HasColumnType("nvarchar(127)")
                        .HasColumnName("full_name_in_arabic");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("ProfileImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("profile_image");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("type");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("user_name");

                    b.Property<int>("UserType")
                        .HasColumnType("int")
                        .HasColumnName("user_type");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_user_email")
                        .HasFilter("[email] IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_user_normalized_email")
                        .HasFilter("[normalized_email] IS NOT NULL");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("ix_user_user_name")
                        .HasFilter("[user_name] IS NOT NULL");

                    b.ToTable("User", "services");

                    b.HasDiscriminator<string>("Type").HasValue("BaseUser");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Kollity.Services.Domain.Messages.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<string>("Error")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("error");

                    b.Property<DateTime>("OccuredOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("occured_on");

                    b.Property<DateTime?>("ProcessedOn")
                        .HasColumnType("datetime2")
                        .HasColumnName("processed_on");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_outbox_message");

                    b.HasIndex("ProcessedOn")
                        .HasDatabaseName("ix_outbox_message_processed_on");

                    b.ToTable("OutboxMessage", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.MessagePollAnswer", b =>
                {
                    b.Property<Guid>("PollId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("poll_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.Property<byte>("OptionIndex")
                        .HasColumnType("tinyint")
                        .HasColumnName("option_index");

                    b.HasKey("PollId", "UserId")
                        .HasName("pk_message_poll_answer");

                    b.HasIndex("OptionIndex")
                        .HasDatabaseName("ix_message_poll_answer_option_index");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_message_poll_answer_user_id");

                    b.ToTable("MessagePollAnswer", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.Room", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<byte>("AssignmentGroupMaxLength")
                        .HasColumnType("tinyint")
                        .HasColumnName("assignment_group_max_length");

                    b.Property<bool>("AssignmentGroupOperationsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("assignment_group_operations_enabled");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<Guid?>("DoctorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("doctor_id");

                    b.Property<bool>("EnsureJoinRequest")
                        .HasColumnType("bit")
                        .HasColumnName("ensure_join_request");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(227)
                        .HasColumnType("nvarchar(227)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_room");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_room_course_id");

                    b.HasIndex("DoctorId")
                        .HasDatabaseName("ix_room_doctor_id");

                    b.ToTable("Room", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.RoomContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)")
                        .HasColumnName("file_path");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(511)
                        .HasColumnType("nvarchar(511)")
                        .HasColumnName("name");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.Property<DateTime>("UploadTime")
                        .HasColumnType("datetime2")
                        .HasColumnName("upload_time");

                    b.Property<Guid?>("UploaderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploader_id");

                    b.HasKey("Id")
                        .HasName("pk_room_content");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_content_room_id");

                    b.HasIndex("UploaderId")
                        .HasDatabaseName("ix_room_content_uploader_id");

                    b.ToTable("RoomContent", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.RoomMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("File")
                        .HasMaxLength(1023)
                        .HasColumnType("nvarchar(1023)")
                        .HasColumnName("file");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Poll")
                        .HasMaxLength(3550)
                        .HasColumnType("nvarchar(3550)")
                        .HasColumnName("poll");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.Property<Guid?>("SenderId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("sender_id");

                    b.Property<string>("Text")
                        .HasMaxLength(4067)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_room_message");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_room_message_room_id");

                    b.HasIndex("SenderId")
                        .HasDatabaseName("ix_room_message_sender_id");

                    b.ToTable("RoomMessage", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.UserRoom", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<bool>("IsSupervisor")
                        .HasColumnType("bit")
                        .HasColumnName("is_supervisor");

                    b.Property<bool>("JoinRequestAccepted")
                        .HasColumnType("bit")
                        .HasColumnName("join_request_accepted");

                    b.Property<DateTime>("LastOnlineDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_online_date");

                    b.Property<Guid>("RoomId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("room_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_room");

                    b.HasIndex("IsSupervisor")
                        .HasDatabaseName("ix_user_room_is_supervisor");

                    b.HasIndex("RoomId")
                        .HasDatabaseName("ix_user_room_room_id");

                    b.HasIndex("UserId", "RoomId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_room_user_id_room_id");

                    b.ToTable("UserRoom", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.StudentModels.StudentCourse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("course_id");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("student_id");

                    b.HasKey("Id")
                        .HasName("pk_student_course");

                    b.HasIndex("CourseId")
                        .HasDatabaseName("ix_student_course_course_id");

                    b.HasIndex("StudentId", "CourseId")
                        .IsUnique()
                        .HasDatabaseName("ix_student_course_student_id_course_id");

                    b.ToTable("StudentCourse", "services");
                });

            modelBuilder.Entity("Kollity.Services.Domain.DoctorModels.Doctor", b =>
                {
                    b.HasBaseType("Kollity.Services.Domain.Identity.BaseUser");

                    b.HasDiscriminator().HasValue("Doctor");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b26c556f-d543-4a2a-b15a-49fba7751ffa"),
                            Email = "nassermahmoud571@gmail.com",
                            EnabledEmailNotifications = false,
                            FullNameInArabic = "Mahmoud Ahmed Nasser Mahmoud",
                            NormalizedEmail = "NASSERMAHMOUD571@GMAIL.COM",
                            NormalizedUserName = "MAHMOUDHD134",
                            UserName = "Mahmoudhd134",
                            UserType = 0
                        });
                });

            modelBuilder.Entity("Kollity.Services.Domain.StudentModels.Student", b =>
                {
                    b.HasBaseType("Kollity.Services.Domain.Identity.BaseUser");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("code");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_user_code")
                        .HasFilter("[code] IS NOT NULL");

                    b.HasDiscriminator().HasValue("Student");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.Assignment", b =>
                {
                    b.HasOne("Kollity.Services.Domain.DoctorModels.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_assigment_users_doctor_id");

                    b.HasOne("Kollity.Services.Domain.RoomModels.Room", "Room")
                        .WithMany("Assignments")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assigment_rooms_room_id");

                    b.Navigation("Doctor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentAnswer", b =>
                {
                    b.HasOne("Kollity.Services.Domain.AssignmentModels.AssignmentGroupModels.AssignmentGroup", "AssignmentGroup")
                        .WithMany("AssignmentsAnswers")
                        .HasForeignKey("AssignmentGroupId")
                        .HasConstraintName("fk_assignment_answer_assignment_groups_assignment_group_id");

                    b.HasOne("Kollity.Services.Domain.AssignmentModels.Assignment", "Assignment")
                        .WithMany("AssignmentsAnswers")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_answer_assignments_assignment_id");

                    b.HasOne("Kollity.Services.Domain.StudentModels.Student", "Student")
                        .WithMany("AssignmentsAnswers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_assignment_answer_users_student_id");

                    b.Navigation("Assignment");

                    b.Navigation("AssignmentGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentAnswerDegree", b =>
                {
                    b.HasOne("Kollity.Services.Domain.AssignmentModels.AssignmentAnswer", "Answer")
                        .WithMany("GroupDegrees")
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_answer_degree_assignment_answer_answer_id");

                    b.HasOne("Kollity.Services.Domain.AssignmentModels.Assignment", "Assignment")
                        .WithMany()
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_answer_degree_assignments_assignment_id");

                    b.HasOne("Kollity.Services.Domain.AssignmentModels.AssignmentGroupModels.AssignmentGroup", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_answer_degree_assignment_groups_group_id");

                    b.HasOne("Kollity.Services.Domain.StudentModels.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_answer_degree_users_student_id");

                    b.Navigation("Answer");

                    b.Navigation("Assignment");

                    b.Navigation("Group");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentFile", b =>
                {
                    b.HasOne("Kollity.Services.Domain.AssignmentModels.Assignment", "Assignment")
                        .WithMany("AssignmentFiles")
                        .HasForeignKey("AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_file_assigment_assignment_id");

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentGroupModels.AssignmentGroup", b =>
                {
                    b.HasOne("Kollity.Services.Domain.RoomModels.Room", "Room")
                        .WithMany("AssignmentGroups")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_group_rooms_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentGroupModels.AssignmentGroupStudent", b =>
                {
                    b.HasOne("Kollity.Services.Domain.AssignmentModels.AssignmentGroupModels.AssignmentGroup", "AssignmentGroup")
                        .WithMany("AssignmentGroupsStudents")
                        .HasForeignKey("AssignmentGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_group_student_assignment_group_assignment_group_id");

                    b.HasOne("Kollity.Services.Domain.StudentModels.Student", "Student")
                        .WithMany("AssignmentGroupsStudents")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_assignment_group_student_users_student_id");

                    b.Navigation("AssignmentGroup");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kollity.Services.Domain.CourseModels.Course", b =>
                {
                    b.HasOne("Kollity.Services.Domain.DoctorModels.Doctor", "Doctor")
                        .WithMany("Courses")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_course_users_doctor_id");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Kollity.Services.Domain.CourseModels.CourseAssistant", b =>
                {
                    b.HasOne("Kollity.Services.Domain.DoctorModels.Doctor", "Assistant")
                        .WithMany("CoursesAssistants")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_course_assistant_users_assistant_id");

                    b.HasOne("Kollity.Services.Domain.CourseModels.Course", "Course")
                        .WithMany("CoursesAssistants")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_course_assistant_courses_course_id");

                    b.Navigation("Assistant");

                    b.Navigation("Course");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.Exam", b =>
                {
                    b.HasOne("Kollity.Services.Domain.RoomModels.Room", "Room")
                        .WithMany("Exams")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_rooms_room_id");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.ExamAnswer", b =>
                {
                    b.HasOne("Kollity.Services.Domain.ExamModels.Exam", "Exam")
                        .WithMany("Answers")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("fk_exam_answer_exams_exam_id");

                    b.HasOne("Kollity.Services.Domain.ExamModels.ExamQuestion", "ExamQuestion")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_answer_exam_questions_exam_question_id");

                    b.HasOne("Kollity.Services.Domain.ExamModels.ExamQuestionOption", "ExamQuestionOption")
                        .WithMany("ExamAnswers")
                        .HasForeignKey("ExamQuestionOptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("fk_exam_answer_exam_question_options_exam_question_option_id");

                    b.HasOne("Kollity.Services.Domain.StudentModels.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_exam_answer_users_student_id");

                    b.Navigation("Exam");

                    b.Navigation("ExamQuestion");

                    b.Navigation("ExamQuestionOption");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.ExamQuestion", b =>
                {
                    b.HasOne("Kollity.Services.Domain.ExamModels.Exam", "Exam")
                        .WithMany("ExamQuestions")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_question_exam_exam_id");

                    b.Navigation("Exam");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.ExamQuestionOption", b =>
                {
                    b.HasOne("Kollity.Services.Domain.ExamModels.ExamQuestion", "ExamQuestion")
                        .WithMany("ExamQuestionOptions")
                        .HasForeignKey("ExamQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_exam_question_option_exam_question_exam_question_id");

                    b.Navigation("ExamQuestion");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.MessagePollAnswer", b =>
                {
                    b.HasOne("Kollity.Services.Domain.RoomModels.RoomMessage", "Poll")
                        .WithMany("PollAnswers")
                        .HasForeignKey("PollId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_poll_answer_room_messages_poll_id");

                    b.HasOne("Kollity.Services.Domain.Identity.BaseUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_message_poll_answer_user_user_id");

                    b.Navigation("Poll");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.Room", b =>
                {
                    b.HasOne("Kollity.Services.Domain.CourseModels.Course", "Course")
                        .WithMany("Rooms")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_course_course_id");

                    b.HasOne("Kollity.Services.Domain.DoctorModels.Doctor", "Doctor")
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_room_user_doctor_id");

                    b.Navigation("Course");

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.RoomContent", b =>
                {
                    b.HasOne("Kollity.Services.Domain.RoomModels.Room", "Room")
                        .WithMany("RoomContents")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_content_room_room_id");

                    b.HasOne("Kollity.Services.Domain.Identity.BaseUser", "Uploader")
                        .WithMany()
                        .HasForeignKey("UploaderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_room_content_user_uploader_id");

                    b.Navigation("Room");

                    b.Navigation("Uploader");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.RoomMessage", b =>
                {
                    b.HasOne("Kollity.Services.Domain.RoomModels.Room", "Room")
                        .WithMany("RoomMessages")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_room_message_room_room_id");

                    b.HasOne("Kollity.Services.Domain.Identity.BaseUser", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_room_message_user_sender_id");

                    b.Navigation("Room");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.UserRoom", b =>
                {
                    b.HasOne("Kollity.Services.Domain.RoomModels.Room", "Room")
                        .WithMany("UsersRooms")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_room_room_room_id");

                    b.HasOne("Kollity.Services.Domain.Identity.BaseUser", "User")
                        .WithMany("UsersRooms")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_room_user_user_id");

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Kollity.Services.Domain.StudentModels.StudentCourse", b =>
                {
                    b.HasOne("Kollity.Services.Domain.CourseModels.Course", "Course")
                        .WithMany("StudentsCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_course_course_course_id");

                    b.HasOne("Kollity.Services.Domain.StudentModels.Student", "Student")
                        .WithMany("StudentsCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_student_course_user_student_id");

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.Assignment", b =>
                {
                    b.Navigation("AssignmentFiles");

                    b.Navigation("AssignmentsAnswers");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentAnswer", b =>
                {
                    b.Navigation("GroupDegrees");
                });

            modelBuilder.Entity("Kollity.Services.Domain.AssignmentModels.AssignmentGroupModels.AssignmentGroup", b =>
                {
                    b.Navigation("AssignmentGroupsStudents");

                    b.Navigation("AssignmentsAnswers");
                });

            modelBuilder.Entity("Kollity.Services.Domain.CourseModels.Course", b =>
                {
                    b.Navigation("CoursesAssistants");

                    b.Navigation("Rooms");

                    b.Navigation("StudentsCourses");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.Exam", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("ExamQuestions");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.ExamQuestion", b =>
                {
                    b.Navigation("ExamAnswers");

                    b.Navigation("ExamQuestionOptions");
                });

            modelBuilder.Entity("Kollity.Services.Domain.ExamModels.ExamQuestionOption", b =>
                {
                    b.Navigation("ExamAnswers");
                });

            modelBuilder.Entity("Kollity.Services.Domain.Identity.BaseUser", b =>
                {
                    b.Navigation("UsersRooms");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.Room", b =>
                {
                    b.Navigation("AssignmentGroups");

                    b.Navigation("Assignments");

                    b.Navigation("Exams");

                    b.Navigation("RoomContents");

                    b.Navigation("RoomMessages");

                    b.Navigation("UsersRooms");
                });

            modelBuilder.Entity("Kollity.Services.Domain.RoomModels.RoomMessage", b =>
                {
                    b.Navigation("PollAnswers");
                });

            modelBuilder.Entity("Kollity.Services.Domain.DoctorModels.Doctor", b =>
                {
                    b.Navigation("Courses");

                    b.Navigation("CoursesAssistants");
                });

            modelBuilder.Entity("Kollity.Services.Domain.StudentModels.Student", b =>
                {
                    b.Navigation("AssignmentGroupsStudents");

                    b.Navigation("AssignmentsAnswers");

                    b.Navigation("StudentsCourses");
                });
#pragma warning restore 612, 618
        }
    }
}
