version: "3.8"

services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Mahmoud2320030@"
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql
    networks:
      - api-and-mssql
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    environment:
      CONNECTION_STRING: "server=mssql,1433;database=Kollity;user id=sa;password=Mahmoud2320030@;encrypt=false;"
    networks:
      - api-and-mssql
    depends_on:
      - mssql
  
  mq:
    container_name: MessageQueue
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - D:\rabbitmq\log:/var/log/rabbitmq
      - D:\rabbitmq\data:/var/data/rabbitmq

volumes:
  sqlvolume:

networks:
  api-and-mssql:
